version: '3'

services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  cache-redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379

  queue-redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6380:6380